### ISSUE TITLE
'If' statements fail to generate with error about split()

### ISSUE THREAD

**Issue by davidhoward** [shoaibkamil/asp#32] opened 2012-04-24 06:04 UTC
Cgen seems to expect the Compare AST element to possess a split() method, which it does not. This makes translation of meaningful branches difficult. Minimal code to produce such an error is reproduced below:

``` python
import asp.codegen.ast_tools as ast_tools
import asp.codegen.cpp_ast as cpp_ast
import inspect, ast

def if_test( x ):
    if x != 0:
        return x
    else:
        return 0

if __name__ == '__main__':
    if_src = inspect.getsource( if_test )
    if_ast = ast.parse( if_src.lstrip() )
    nt = ast_tools.ConvertAST()
    c_src = str( nt.visit( if_ast ) )
    print c_src
```

The error is thrown at line 473 of cgen/**init**.py.

**Comment by shoaibkamil** [comment] 2012-04-24 17:16
Fixed with commit 5788be1152.  The issue is a bug in cgen that we'll have to work around for now.

**Closed as completed by shoaibkamil** 2012-04-24 17:16 UTC
